### ISSUE TITLE
PublishSubject does not emmit latest item

### ISSUE THREAD

**Issue by chriswiesner** [JakeWharton/RxReplayingShare#17]
I've got a `PublishSubject` which emmits items when the State of a Service changes.

```
stateSubject = PublishSubject.create()
stateSubject.compose(ReplayingShare.instance());
```

```
void onStateChange(State newState) {
   stateSubject.onNext(newState);
}
```

in my Views (Presenters) i subscribe on that subject and as the Views get destroyed / attach again i want to have the latest state when subscribing again. (--> ReplayingShare)

```
interactor.getServiceStateObservable()
				.subscribeOn(Schedulers.io())
				.observeOn(AndroidSchedulers.mainThread())
				.doOnNext(countdownServiceState -> {
					onStateUpdate(state);
				})
				.subscribe();
```
but it don't get any value when subscribing again.

Did I got anything wrong?

**Comment by JakeWharton** [comment]
It looks like you aren't storing the result of calling compose() and
exposing that Observable to the presenters. You call compose() but ignore
the return value that has the new behavior you want.

**Comment by chriswiesner** [comment]
ah right, sorry.
at first i tried 
```
stateSubject = PublishSubject.create().compose(ReplayingShare.instance());
```

but it's not possible to chain it like that, so i "accidently" just split it.

**Comment by chriswiesner** [comment]
Still struggling but found my initial failure.
I tried to apply `compose()` on the Subject and reassign it, but `compose()` returns an Observable so that's not possible here.
So i applied the `compose()` when exposing the Subject.
But i still don't get the previous value then.

My Presenter get's destroyed when the view is destroyed. The Interactor (which holds the Subject)  lives on. It exposes it like:

```
public Observable<ServiceState> getServiceStateObservable() {
		return stateSubject.compose(ReplayingShare.instance());
}
```

As a new View/Presenter then subscribes to the Subject, i doesn't deliver the last value.
