### ISSUE TITLE
What different between this lib and Operator .replay(1).autoConnect()?

### ISSUE THREAD

**Issue by wbinarytree** [JakeWharton/RxReplayingShare#20]
I listened to the http://fragmentedpodcast.com/episodes/053-jake-wharton-on-rxjava-2/ about this lib. But somehow I feel replay(1).autoConnect() do the same with this lib? Could you please explain a bit about this?

**Comment by JakeWharton** [comment]
That will never disconnect from the upstream.

From the README (emphasis added):

> Unlike traditional combinations of these operators, `ReplayingShare` caches the last emitted value from the upstream observable or flowable **only when one or more downstream subscribers are connected**. This allows expensive upstream sources to be shut down when no one is listening while also replaying the last value seen by any subscriber to new ones.

**Comment by stavfx** [comment]
I understand how it's different from autoConnect, but I'm trying to understand the difference between this operator and `replay(1).refCount()`.
>Any terminal event will clear the cached value.

^ That's true for both ReplayingShare and replay.refCount.
They'll also both disconnect from the upstream when they hit 0 subscribers. Is the difference that the cached value will be retained in this case with ReplayingShare, while `replay(1).refCount()` will treat that case just like a terminal event and discard the cached value?

**Comment by JakeWharton** [comment]
Precisely!
