### ISSUE TITLE
how to invalidate the cache some time

### ISSUE THREAD

**Issue by shakil807g** [JakeWharton/RxReplayingShare#24]
i want to re subscribe to upper  stream in order to fetch new data some time how can i achive it ??

**Comment by JakeWharton** [comment]
This is not supported. If you want to cause a resubscription you'll have to do it outside the replaying share operator such as with a separate timer. I would suggest asking on StackOverflow with the 'rxjava' tag as this is applicable to any observable, not just ones with the replaying share operator applied.
