### ISSUE TITLE
Put a chart in the README comparing other operator combinations

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxReplayingShare#33]
At least covering `share()` (aka `publish().refCount()`), `replay(1).refCount()`, and `replay(1).autoConnect()` and the differences to this operator.

**Comment by JakeWharton** [comment]
I've already forgotten the differences. I can see why others don't understand. Here's a first pass:


|                                                                                  | replayingShare() | replay(1).refCount() | publish().refCount() |   |
|----------------------------------------------------------------------------------|------------------|----------------------|----------------------|---|
| Disconnects from upstream when there are no subscribers                          | ✅                | ✅                    | ✅                    |   |
| Replays the latest value to new subscribers when other subscribers are active    | ✅                | ✅                    | ❌                    |   |
| Replays the latest value to new subscribers when no other subscribers are active | ✅                | ❌                    | ❌                    |   |

**Comment by JakeWharton** [comment]
I'm just going to put this in and we can iterate from there...

**Comment by oldergod** [comment]
That's super helpful yes

**Comment by JakeWharton** [comment]
63f040d7039df4f8750f8af05d3e7154cb4a7f3e
