### ISSUE TITLE
[ Question ] Kotlin flow equivalent

### ISSUE THREAD

**Issue by tperraut** [JakeWharton/RxReplayingShare#36]
Is there an equivalent of this awesome Rx helper for Kotlin Flow ?

**Comment by JakeWharton** [comment]
No. Flow lacks the concept of share. If you need this functionality with a `Flow` please add a description of your use case to https://github.com/Kotlin/kotlinx.coroutines/issues/1261 or file a new issue on the project and perhaps it will be supported directly.
