### ISSUE TITLE
About section inaccurately refers to RxJava 2

### ISSUE THREAD

**Issue by DavidDTA** [JakeWharton/RxReplayingShare#41]
The about section of this repo, and consequently the Google search snippet, calls ReplayingShare "An RxJava 2 transformer", while the readme calls it "an RxJava 3 transformer".  The About section should be updated to match the readme.

**Comment by JakeWharton** [comment]
I removed the number. The version history supports RxJava 1, 2, and 3. We actually should update the README to reflect this fact rather than having it be hidden in the git history.

**Comment by JakeWharton** [comment]
I'll update it next week.

**Comment by JakeWharton** [comment]
6761db704876de6c8d7a5a08c330629a7c2957d0
